fixed minor issues

diff --git a/bspwm/bin/bspTheme b/bspwm/bin/bspTheme
--- a/bspwm/bin/bspTheme
+++ b/bspwm/bin/bspTheme
@@ -1,4 +1,11 @@
 #!/bin/bash
+
+if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
+    echo -e "./applyTheme < number | nothing >"
+    echo -e "put number 1 to regen wal"
+    echo -e "no number , no regen"
+fi
+
 # using pywal
 override=$1               # means must regen wal even if it is gened
 walToggle=0               # means must regen wal if alreay gened, no need
@@ -8,10 +15,10 @@ DIR="$HOME/.config/bspwm/"
 
 ## -_-_-_-_-_-_-_-_-_ Source wal colors -_-_-_-_-_-_-_-_-_ ##
 
-# source the color wal generated
+### source the color wal generated
 function sourcewal() {
-	echo -e "\e[32m[*] \e[0mApplying Theme"
-	[ -f "$HOME/.cache/wal/colors.sh" ] && source "$HOME/.cache/wal/colors.sh" || walToggle=1
+    echo -e "Applying Theme"
+    [ -f "$HOME/.cache/wal/colors.sh" ] && source "$HOME/.cache/wal/colors.sh" || walToggle=1
 }
 
 ### getting the theme colors
@@ -19,169 +26,169 @@ sourcewal
 
 ### checks
 if [ $walToggle -eq 1 ] || [ "$override" != "" ]; then
-	[ -f "$wallpaperdir" ] && [ -f /bin/wal ] && wal -c || {
-		echo "wall not installed or wallpaper not found"
-		exit 1
-	}
-
-	echo -e "\e[32m[*] \e[0mSetting wallpaper..."
-	cp "$wallpaperdir" "$HOME/.wallpaper.png" >>~/log.txt 2>&1
-	[ "$backend" = "" ] && backend="wal"
-	wal -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1 || {
-		echo "wallpaper or backend not found using default: wal"
-		echo "wal" >~/.backend && backend="wal"
-		wal -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1
-	}
-	echo -e "\e[32m[*] \e[0mGenerating Theme..."
-	sourcewal
-
+    [ -f "$wallpaperdir" ] && [ -f /bin/wal ] && wal -c || {
+        echo "wall not installed or wallpaper not found"
+            exit 1
+        }
+        echo -e "Setting wallpaper..."
+        cp "$wallpaperdir" "$HOME/.wallpaper.png" >>~/log.txt 2>&1
+        [ "$backend" = "" ] && backend="wal"
+        wal -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1 || {
+            echo "wallpaper or backend not found using default: wal"
+                    echo "wal" >~/.backend && backend="wal"
+                    wal -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1
+                }
+                echo -e "Generating Theme..."
+                sourcewal
 fi
 
 ## -_-_-_-_-_-_-_-_-_ Assign Colors -_-_-_-_-_-_-_-_-_ ##
+
 getcolors() {
-	FOREGROUND="$foreground"
-	BACKGROUND="$background"
-	CURSOR="$cursor"
-	BLACK="$color0"
-	RED="$color1"
-	GREEN="$color2"
-	YELLOW="$color3"
-	BLUE="$color4"
-	MAGENTA="$color5"
-	CYAN="$color6"
-	WHITE="$color7"
-	ALTBLACK="$color8"
-	ALTRED="$color9"
-	ALTGREEN="$color10"
-	ALTYELLOW="$color11"
-	ALTBLUE="$color12"
-	ALTMAGENTA="$color13"
-	ALTCYAN="$color14"
-	ALTWHITE="$color15"
+    FOREGROUND="$foreground"
+    BACKGROUND="$background"
+    CURSOR="$cursor"
+    BLACK="$color0"
+    RED="$color1"
+    GREEN="$color2"
+    YELLOW="$color3"
+    BLUE="$color4"
+    MAGENTA="$color5"
+    CYAN="$color6"
+    WHITE="$color7"
+    ALTBLACK="$color8"
+    ALTRED="$color9"
+    ALTGREEN="$color10"
+    ALTYELLOW="$color11"
+    ALTBLUE="$color12"
+    ALTMAGENTA="$color13"
+    ALTCYAN="$color14"
+    ALTWHITE="$color15"
 }
 
-## Write polybar colors file with current theme colors
-polybarTheme() {
-	echo -e "\e[32m[*] \e[0mApplying colors to polybar"
-	cat >"$DIR"/polybar/colors.ini <<-EOF
-		[color]
-		foreground =    ${FOREGROUND}
-		background =    ${BACKGROUND}
-		primary =       ${CURSOR}
+### Write polybar colors file with current theme colors
+function polybarTheme() {
+echo "Applying colors to polybar"
+cat<<EOF >$DIR/polybar/colors.ini
+    [color]
+    foreground =    ${FOREGROUND}
+    background =    ${BACKGROUND}
+    primary =       ${CURSOR}
 
-		workcolor =     ${FOREGROUND} 
-		red =           ${RED}
-		green =         ${GREEN}
-		yellow =        ${YELLOW}
-	EOF
+    workcolor =     ${FOREGROUND}
+    red =           ${RED}
+    green =         ${GREEN}
+    yellow =        ${YELLOW}
+EOF
 }
 
-## Write i3colors
+### Write i3colors
 i3Theme() {
-	echo -e "\e[32m[*] \e[0mApplying colors to i3"
-	cat >"$DIR"/i3colors <<-_EOF_
-		# class                 border  backgr. text    indicator child_border
-		client.focused          #DA6E89 #DA6E89 #FFFFFF #98C379   #DA6E89
-		client.focused_inactive #61AFEF #61AFEF #1E222A #98C379   #61AFEF
-		client.unfocused        #2C3038 #2C3038 #FFFFFF #98C379   #2C3038
-		client.urgent           #C678DD #C678DD #FFFFFF #98C379   #C678DD
-		client.placeholder      #1E222A #1E222A #FFFFFF #98C379   #1E222A
-		client.background       #1E222A
-	_EOF_
+echo  "Applying colors to i3"
+cat  <<EOF >$DIR/i3colors
+    # class                 border  backgr. text    indicator child_border
+    client.focused          ${FOREGROUND} ${FOREGROUND} ${MAGENTA} ${RED}   ${FOREGROUND}
+    client.focused_inactive ${BACKGROUND} ${BACKGROUND} ${BACKGROUND} ${RED}   ${BACKGROUND}
+    client.unfocused        ${BACKGROUND} ${BACKGROUND} ${MAGENTA} ${RED}   ${BACKGROUND}
+    client.urgent           ${GREEN} ${GREEN} ${MAGENTA} ${RED}   ${GREEN}
+    client.placeholder      ${BACKGROUND} ${BACKGROUND} ${MAGENTA} ${RED}   ${BACKGROUND}
+    client.background       ${BACKGROUND}
+EOF
+i3-msg -t command reload
 }
 
-## Write alacritty colors.yml file with current theme colors
-alacrittyTheme() {
-	echo -e "\e[32m[*] \e[0mApplying colors to Alacritty"
-	cat >"$DIR"/alacritty/colors.yml <<-_EOF_
-		## Colors configuration
-		colors:
-		  # Default colors
-		  primary:
-		    background: '${BACKGROUND}'
-		    foreground: '${FOREGROUND}'
+### Write alacritty colors.yml file with current theme colors
+function alacrittyTheme() {
+echo -e "Applying colors to Alacritty"
+cat  <<EOF >$DIR/alacritty/colors.toml
+    [colors.bright]
+    black = "${ALTBLACK}"
+    blue = "${ALTBLUE}"
+    cyan = "${ALTCYAN}"
+    green = "${ALTGREEN}"
+    magenta = "${ALTMAGENTA}"
+    red = "${ALTRED}"
+    white = "${ALTWHITE}"
+    yellow = "${ALTYELLOW}"
 
-		  # Normal colors
-		  normal:
-		    black:   '${BLACK}'
-		    red:     '${RED}'
-		    green:   '${GREEN}'
-		    yellow:  '${YELLOW}'
-		    blue:    '${BLUE}'
-		    magenta: '${MAGENTA}'
-		    cyan:    '${CYAN}'
-		    white:   '${WHITE}'
+    [colors.normal]
+    black = "${ALTBLACK}"
+    blue = "${ALTBLUE}"
+    cyan = "${ALTCYAN}"
+    green = "${ALTGREEN}"
+    magenta = "${ALTMAGENTA}"
+    red = "${ALTRED}"
+    white = "${ALTWHITE}"
+    yellow = "${ALTYELLOW}"
 
-		  # Bright colors
-		  bright:
-		    black:   '${ALTBLACK}'
-		    red:     '${ALTRED}'
-		    green:   '${ALTGREEN}'
-		    yellow:  '${ALTYELLOW}'
-		    blue:    '${ALTBLUE}'
-		    magenta: '${ALTMAGENTA}'
-		    cyan:    '${ALTCYAN}'
-		    white:   '${ALTWHITE}'
-	_EOF_
-}
-kittyTheme() {
-	echo -e "\e[32m[*] \e[0mApplying colors to Kitty"
-	[ -f ~/.cache/wal/colors-kitty.conf ] && cp ~/.cache/wal/colors-kitty.conf ../kitty/color.conf
+    [colors.primary]
+    background = "${BACKGROUND}"
+    foreground = "${FOREGROUND}"
+EOF
 }
 
-## Write rofi colors.rasi file with current theme colors
-rofiTheme() {
-	echo -e "\e[32m[*] \e[0mApplying colors to rofi"
-	cat >"$DIR"/rofi/dependencies/colors.rasi <<-EOF
-		* {
-		    background:         ${BACKGROUND};
-		    background-alt:     ${CURSOR};
-		    foreground:         ${FOREGROUND};
-		    selected:           ${BLUE};
-		    active:             ${YELLOW};
-		    urgent:             ${RED};
-		}
-	EOF
+### kitty-Theme
+function kittyTheme() {
+    echo -e "Applying colors to Kitty"
+    [ -f ~/.cache/wal/colors-kitty.conf ] && cp ~/.cache/wal/colors-kitty.conf ../kitty/color.conf
 }
 
-## Write dunstrc file with current theme colors
+### Write rofi colors.rasi file with current theme colors
+function rofiTheme() {
+echo -e "Applying colors to rofi"
+cat  <<EOF >"$DIR"/rofi/dependencies/colors.rasi
+    * {
+        background:         ${BACKGROUND};
+        background-alt:     ${CURSOR};
+        foreground:         ${FOREGROUND};
+        selected:           ${BLUE};
+        active:             ${YELLOW};
+        urgent:             ${RED};
+    }
+EOF
+}
+
+### Write dunstrc file with current theme colors
 dunstTheme() {
-	echo -e "\e[32m[*] \e[0mApplying colors to dunst"
-	sed -i '/urgency_low/Q' "$DIR"/others/dunstrc
-	cat >>"$DIR"/others/dunstrc <<-_EOF_
-		[urgency_low]
-		timeout = 3
-		background =   "${BACKGROUND}"
-		foreground =   "${FOREGROUND}"
-		frame_color =  "${BLUE}"
+echo -e "Applying colors to dunst"
+sed -i '/urgency_low/Q' "$DIR"/others/dunstrc
+cat <<EOF >>"$DIR"/dunstrc 
+    [urgency_low]
+    timeout = 3
+    background =   "${BACKGROUND}"
+    foreground =   "${FOREGROUND}"
+    frame_color =  "${BLUE}"
 
-		[urgency_normal]
-		timeout = 5
-		background =   "${BACKGROUND}"
-		foreground =   "${FOREGROUND}"
-		frame_color =  "${BLUE}"
+    [urgency_normal]
+    timeout = 5
+    background =   "${BACKGROUND}"
+    foreground =   "${FOREGROUND}"
+    frame_color =  "${BLUE}"
 
-		[urgency_critical]
-		timeout = 0
-		background =   "${BACKGROUND}"
-		foreground =   "${FOREGROUND}"
-		frame_color =  "${RED}"
-	_EOF_
+    [urgency_critical]
+    timeout = 0
+    background =   "${BACKGROUND}"
+    foreground =   "${FOREGROUND}"
+    frame_color =  "${RED}"
+EOF
 }
 
+### firefox-pywal
 firefoxTheme() {
-	echo -e "\e[32m[*] \e[0mApplying colors to Firefox"
-	[ -f /bin/firefox ] && [ -f /bin/pywalfox ] && [ -f /bin/wal ] && pywalfox install >/dev/null 2>&1 || echo -e "\e[32m[ERR] \e[0mfirefox pywal failed or not found\n"
+    echo -e "Applying colors to Firefox"
+    [ -f /bin/firefox ] && [ -f /bin/pywalfox ] && [ -f /bin/wal ] && pywalfox install >/dev/null 2>&1 || echo -e "firefox pywal failed or not found\n"
 }
 
-## Execute functions and run main
+### Execute functions and run main
 main() {
-	getcolors
-	polybarTheme
-	alacrittyTheme
-	rofiTheme
-	dunstTheme
-	#kittyTheme
-	firefoxTheme
+    getcolors
+   # i3Theme
+    polybarTheme
+    alacrittyTheme
+    rofiTheme
+    dunstTheme
+    #kittyTheme
+    firefoxTheme
 }
+
 main
