Major Fixes to Issues : Fonts, NetworkManager, ApplyTheme
Polybar may Still not work

diff --git a/i3/bin/applyTheme b/i3/bin/applyTheme
--- a/i3/bin/applyTheme
+++ b/i3/bin/applyTheme
@@ -6,12 +6,17 @@ if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
     echo -e "no number , no regen"
 fi
 
-# using pywal
+# will use python module or wal binary
+walbinary=""
+[ -f /usr/bin/wal ] && walbinary="wal " || walbinary="python3 -m pywal "
+
+# using wal backend
+[ ! -f ~/backend  ] && echo "wal" > ~/.backend
 override=$1               # means must regen wal even if it is gened
 walToggle=0               # means must regen wal if alreay gened, no need
 backend=$(cat ~/.backend) # the backend to use
-wallpaperdir="$HOME/.config/i3/wallpaper/wallpaper.png"
 DIR="$HOME/.config/i3/"
+wallpaperdir="$DIR/wallpaper/wallpaper.png"
 
 ## -_-_-_-_-_-_-_-_-_ Source wal colors -_-_-_-_-_-_-_-_-_ ##
 
@@ -25,18 +30,33 @@ function sourcewal() {
 sourcewal
 
 ### checks
-if [ $walToggle -eq 1 ] || [ "$override" != "" ]; then
-    [ -f "$wallpaperdir" ] && [ -f /bin/wal ] && wal -c || {
-        echo "wall not installed or wallpaper not found"
+if [ $walToggle -eq 1 ] || [ ! -z "$override"  ]; then
+    # looking for wallpaper
+    if [ ! -f "$wallpaperdir" ];then
+       wallpaperdir="$DIR/wallpaper.png"
+       if [ -f $wallpaperdir ];then
+           echo "wallpaper found"
+        else 
+            echo "wallpaper not found" 
+            echo "$DIR/wallpaper.png OR ~/.config/wallpaper/wallpaper.png"
             exit 1
-        }
+       fi
+    fi
+
+    $walbinary -c || {
+        echo "pywal not found, use pip install pywal or your packagemanager"
+        exit 1
+    }
+
         echo -e "Setting wallpaper..."
         cp "$wallpaperdir" "$HOME/.wallpaper.png" >>~/log.txt 2>&1
+        
+        echo "running pywall on wallpaper"
         [ "$backend" = "" ] && backend="wal"
-        wal -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1 || {
+        $walbinary -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1 || {
             echo "wallpaper or backend not found using default: wal"
                     echo "wal" >~/.backend && backend="wal"
-                    wal -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1
+                    $walbinary -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1
                 }
                 echo -e "Generating Theme..."
                 sourcewal
@@ -69,6 +89,7 @@ getcolors() {
 ### Write polybar colors file with current theme colors
 function polybarTheme() {
 echo "Applying colors to polybar"
+[ ! -f "$DIR/polybar/colors.ini" ] && touch  "$DIR/polybar/colors.ini"
 cat<<EOF >$DIR/polybar/colors.ini
     [color]
     foreground =    ${FOREGROUND}
@@ -85,6 +106,7 @@ EOF
 ### Write i3colors
 i3Theme() {
 echo  "Applying colors to i3"
+[ ! -f "$DIR/i3colors" ] && touch  "$DIR/i3colors"
 cat  <<EOF >$DIR/i3colors
     # class                 border  backgr. text    indicator child_border
     client.focused          ${FOREGROUND} ${FOREGROUND} ${MAGENTA} ${RED}   ${FOREGROUND}
@@ -100,6 +122,7 @@ i3-msg -t command reload
 ### Write alacritty colors.yml file with current theme colors
 function alacrittyTheme() {
 echo -e "Applying colors to Alacritty"
+[ ! -f "$DIR/alacritty/colors.toml" ] && touch  "$DIR/alacritty/colors.toml"
 cat  <<EOF >$DIR/alacritty/colors.toml
     [colors.bright]
     black = "${ALTBLACK}"
@@ -136,6 +159,7 @@ function kittyTheme() {
 ### Write rofi colors.rasi file with current theme colors
 function rofiTheme() {
 echo -e "Applying colors to rofi"
+[ ! -f "$DIR"/rofi/dependencies/colors.rasi ] && touch  "$DIR"/rofi/dependencies/colors.rasi
 cat  <<EOF >"$DIR"/rofi/dependencies/colors.rasi
     * {
         background:         ${BACKGROUND};
