theme fix

diff --git a/i3/bin/applyTheme b/i3/bin/applyTheme
--- a/i3/bin/applyTheme
+++ b/i3/bin/applyTheme
@@ -11,7 +11,7 @@ walbinary=""
 [ -f /usr/bin/wal ] && walbinary="wal " || walbinary="python3 -m pywal "
 
 # using wal backend
-[ ! -f ~/backend  ] && echo "wal" > ~/.backend
+[ ! -f ~/backend ] && echo "wal" >~/.backend
 override=$1               # means must regen wal even if it is gened
 walToggle=0               # means must regen wal if alreay gened, no need
 backend=$(cat ~/.backend) # the backend to use
@@ -30,17 +30,17 @@ function sourcewal() {
 sourcewal
 
 ### checks
-if [ $walToggle -eq 1 ] || [ ! -z "$override"  ]; then
+if [ $walToggle -eq 1 ] || [ ! -z "$override" ]; then
     # looking for wallpaper
-    if [ ! -f "$wallpaperdir" ];then
-       wallpaperdir="$DIR/wallpaper.png"
-       if [ -f $wallpaperdir ];then
-           echo "wallpaper found"
-        else 
-            echo "wallpaper not found" 
+    if [ ! -f "$wallpaperdir" ]; then
+        wallpaperdir="$DIR/wallpaper.png"
+        if [ -f $wallpaperdir ]; then
+            echo "wallpaper found"
+        else
+            echo "wallpaper not found"
             echo "$DIR/wallpaper.png OR ~/.config/wallpaper/wallpaper.png"
             exit 1
-       fi
+        fi
     fi
 
     $walbinary -c || {
@@ -48,18 +48,18 @@ if [ $walToggle -eq 1 ] || [ ! -z "$override"  ]; then
         exit 1
     }
 
-        echo -e "Setting wallpaper..."
-        cp "$wallpaperdir" "$HOME/.wallpaper.png" >>~/log.txt 2>&1
-        
-        echo "running pywall on wallpaper"
-        [ "$backend" = "" ] && backend="wal"
-        $walbinary -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1 || {
-            echo "wallpaper or backend not found using default: wal"
-                    echo "wal" >~/.backend && backend="wal"
-                    $walbinary -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1
-                }
-                echo -e "Generating Theme..."
-                sourcewal
+    echo -e "Setting wallpaper..."
+    cp "$wallpaperdir" "$HOME/.wallpaper.png" >>~/log.txt 2>&1
+
+    echo "running pywall on wallpaper"
+    [ "$backend" = "" ] && backend="wal"
+    $walbinary -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1 || {
+        echo "wallpaper or backend not found using default: wal"
+        echo "wal" >~/.backend && backend="wal"
+        $walbinary -i "$wallpaperdir" --backend "$backend" >>~/log.txt 2>&1
+    }
+    echo -e "Generating Theme..."
+    sourcewal
 fi
 
 ## -_-_-_-_-_-_-_-_-_ Assign Colors -_-_-_-_-_-_-_-_-_ ##
@@ -88,9 +88,9 @@ getcolors() {
 
 ### Write polybar colors file with current theme colors
 function polybarTheme() {
-echo "Applying colors to polybar"
-[ ! -f "$DIR/polybar/colors.ini" ] && touch  "$DIR/polybar/colors.ini"
-cat<<EOF >$DIR/polybar/colors.ini
+    echo "Applying colors to polybar"
+    [ ! -f "$DIR/polybar/colors.ini" ] && touch "$DIR/polybar/colors.ini"
+    cat <<EOF >$DIR/polybar/colors.ini
     [color]
     foreground =    ${FOREGROUND}
     background =    ${BACKGROUND}
@@ -105,9 +105,9 @@ EOF
 
 ### Write i3colors
 i3Theme() {
-echo  "Applying colors to i3"
-[ ! -f "$DIR/i3colors" ] && touch  "$DIR/i3colors"
-cat  <<EOF >$DIR/i3colors
+    echo "Applying colors to i3"
+    [ ! -f "$DIR/i3colors" ] && touch "$DIR/i3colors"
+    cat <<EOF >$DIR/i3colors
     # class                 border  backgr. text    indicator child_border
     client.focused          ${FOREGROUND} ${FOREGROUND} ${MAGENTA} ${RED}   ${FOREGROUND}
     client.focused_inactive ${BACKGROUND} ${BACKGROUND} ${BACKGROUND} ${RED}   ${BACKGROUND}
@@ -116,14 +116,14 @@ cat  <<EOF >$DIR/i3colors
     client.placeholder      ${BACKGROUND} ${BACKGROUND} ${MAGENTA} ${RED}   ${BACKGROUND}
     client.background       ${BACKGROUND}
 EOF
-i3-msg -t command reload
+    i3-msg -t command reload
 }
 
 ### Write alacritty colors.yml file with current theme colors
 function alacrittyTheme() {
-echo -e "Applying colors to Alacritty"
-[ ! -f "$DIR/alacritty/colors.toml" ] && touch  "$DIR/alacritty/colors.toml"
-cat  <<EOF >$DIR/alacritty/colors.toml
+    echo -e "Applying colors to Alacritty"
+    [ ! -f "$DIR/alacritty/colors.toml" ] && touch "$DIR/alacritty/colors.toml"
+    cat <<EOF >$DIR/alacritty/colors.toml
     [colors.bright]
     black = "${ALTBLACK}"
     blue = "${ALTBLUE}"
@@ -158,9 +158,9 @@ function kittyTheme() {
 
 ### Write rofi colors.rasi file with current theme colors
 function rofiTheme() {
-echo -e "Applying colors to rofi"
-[ ! -f "$DIR"/rofi/dependencies/colors.rasi ] && touch  "$DIR"/rofi/dependencies/colors.rasi
-cat  <<EOF >"$DIR"/rofi/dependencies/colors.rasi
+    echo -e "Applying colors to rofi"
+    [ ! -f "$DIR"/rofi/dependencies/colors.rasi ] && touch "$DIR"/rofi/dependencies/colors.rasi
+    cat <<EOF >"$DIR"/rofi/dependencies/colors.rasi
     * {
         background:         ${BACKGROUND};
         background-alt:     ${CURSOR};
@@ -174,9 +174,9 @@ EOF
 
 ### Write dunstrc file with current theme colors
 dunstTheme() {
-echo -e "Applying colors to dunst"
-sed -i '/urgency_low/Q' "$DIR"/dunstrc
-cat <<EOF >>"$DIR"/dunstrc 
+    echo -e "Applying colors to dunst"
+    sed -i '/urgency_low/Q' "$DIR"/dunstrc
+    cat <<EOF >>"$DIR"/dunstrc
     [urgency_low]
     timeout = 3
     background =   "${BACKGROUND}"
@@ -203,6 +203,23 @@ firefoxTheme() {
     [ -f /bin/firefox ] && [ -f /bin/pywalfox ] && [ -f /bin/wal ] && pywalfox install >/dev/null 2>&1 || echo -e "firefox pywal failed or not found\n"
 }
 
+function networkmanger() {
+    echo -e "Applying colors to networkmanager"
+    if [ ! -f ~/.config/networkmanager-dmenu/config.ini ]; then
+        echo -r "Could not find Networkmanager-dmenu"
+        return
+    fi
+    cat <<EOF >~/.config/networkmanager-dmenu/config.ini
+[dmenu]
+dmenu_command = rofi -rofi_highlight=True -l 10 -dmenu -theme ~/.config/i3/rofi/network/network.rasi
+# Note that dmenu_command can contain arguments as well like \$(rofi -width 30)
+# m = number of monitor to display on
+[editor]
+terminal = alacritty
+gui_if_available = True
+EOF
+}
+
 ### Execute functions and run main
 main() {
     getcolors
@@ -213,6 +230,7 @@ main() {
     dunstTheme
     #kittyTheme
     firefoxTheme
+    networkmanger
 }
 
 main
